N: 30
add_augmentation: true
attn_resolutions: []
audio_log_files:
- 3
- 4
- 11
- 17
- 19
- 26
- 29
- 32
audio_log_interval: 5
backbone: ncsnpp_48k
base_dir: /media/DATA/shared/datasets/MSS_datasets
batch_size: 1
c_in: '1'
c_out: '1'
c_skip: '0'
centered: true
ch_mult:
- 1
- 1
- 2
- 2
- 2
- 2
- 2
data_module_cls: !!python/name:sgmsvs.data_module.SpecsDataModule ''
dataset_str: musmoisdb
dummy: false
duration: 5.0
ema_decay: 0.999
format: MSS
full_mix_percentage: 0.5
hop_length: 512
l1_weight: 0.001
loss_type: score_matching
loss_weighting: sigma^2
lr: 0.0001
n_fft: 2046
network_scaling: null
nf: 128
nolog: true
normalize: noisy
num_eval_files: 50
num_res_blocks: 2
num_workers: 10
progressive: none
progressive_input: none
rand_seed: 13
random_mix: true
sampler_type: pc
samples_per_track: 24
sde: ouve
sigma_data: 0.1
sigma_max: 1.0
sigma_min: 0.1
spec_abs_exponent: 0.334
spec_factor: 0.0516
sr: 44100
t_eps: 0.03
target_is_accompaniment: false
target_str: vocals
theta: 2.0
train_mono: true
transform_type: exponent
use_musdb_test_as_valid: true
valid_sep_dir: ./valid_output_scratch_scale_0.0516_comp_0.334_fs44100
valid_split: 0.1
window: hann
